Feature: Nutrient
    Description: A nutrient includes protein, carbs, etc

    # Specifications generated by ChatGPT
    # prompt:
    # write gherkin syntax for creating, retrieving a list of,
    # updating and deleting a nutrient such as Carbohydrates, Proteins, etc

    Scenario: Create a nutrient
        Given a nutrient name
        When I create a nutrient
        Then I should get a nutrient

    Scenario: Retrieve a list of nutrients
        Given a list of nutrients
        When I retrieve a list of nutrients
        Then I should get a list of nutrients

    Scenario: Update a nutrient
        Given a nutrient name
        When I update a nutrient
        Then I should get a nutrient

    Scenario: Delete a nutrient
        Given a nutrient name
        When I delete a nutrient
        Then I should get a nutrient
