Feature: Ingredient
  Description: The ingredient of the recipe

  # Specifications generated by ChatGPT
  # prompt:
  # write gherkin syntax for creating, retrieving a list of, 
  # updating and deleting an existing ingredient, 
  # considering an ingredient can contain one or more nutrients

  Scenario: Create an ingredient
    Given I have an ingredient with the following attributes
      | name | description | nutrients |
      | name | description | nutrients |
    When I create the ingredient
    Then I should get a response with status code 201

  Scenario: Retrieve a list of ingredients
    Given I have a list of ingredients
    When I retrieve the list of ingredients
    Then I should get a response with status code 200
    And the response should contain a list of ingredients

  Scenario: Update an existing ingredient
    Given I have an existing ingredient
    When I update the ingredient with the following attributes
      | name | description | nutrients |
      | name | description | nutrients |
    Then I should get a response with status code 200
    And the response should contain the updated ingredient

  Scenario: Delete an existing ingredient
    Given I have an existing ingredient
    When I delete the ingredient
    Then I should get a response with status code 204
  
